import Head from "next/head";
import { AiFillYoutube } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>LanguageDev Study</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="web-name">LanguageDev Study</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <button className="btn">Get Started</button>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              LanguageDev Study
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Learn programming languages
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://youtube.com/@languagedevstudy"><AiFillYoutube /></a>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Why create the project "LanguageDev Study"?</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              From 2021, HiTECH Corporation begins developing the "LanguageDev Study" project aimed at programming. The project is still in the completion stage. We look forward to receiving your support. Thank you!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="img" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Program
              </h3>
              <h4 className="py-4 text-teal-600">Application used for programming</h4>
              <p className="text-gray-800 py-1">Visual Studio Code (Recommended)</p>
              <p className="text-gray-800 py-1">PyCharm</p>
              <p className="text-gray-800 py-1">Sublime Text</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="img"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code
              </h3>
              <h4 className="py-4 text-teal-600">Programming language</h4>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">NextJS</p>
              <p className="text-gray-800 py-1">etc..</p>
            </div>
          </div>
        </section>
        <h2>Copyright LanguageDev Study © 2023</h2>
      </main>
    </div>
  );
}
